### ISSUE TITLE
Use GraalVM 20.0.0

### ISSUE THREAD

**Issue by liquidz** [liquidz/dad#20]
https://www.graalvm.org/docs/release-notes/20_0/

**Comment by borkdude** [comment]
@liquidz I found a performance regression for macOS in version 20:

https://github.com/oracle/graal/issues/2136

Just for your information.

**Comment by liquidz** [comment]
@borkdude thanks for your notification!

**Comment by borkdude** [comment]
@liquidz To put it in perspective: the startup and performance of graalvm20 on macos is still fast, but I hope they can get back to the original performance.

**Comment by liquidz** [comment]
using 22.0.0.2 now
